#!/usr/bin/env python3

import skilstak.colors as c
import sys

# Functions
def hello(message):
    print(c.rc() + "Hello, " + message + "!")

def nyan(message):
    while True:
        print(c.rc() + "Hello, " + message, end = " ")


# Code
if __name__ == "__main__":
    if len(sys.argv) == 2:
        nyan(sys.argv[1])
    elif len(sys.argv) == 1:
        hello("world")
