#!/usr/bin/env python3
import lelstuff as l
if __name__ == "__main__":
    import sys
    option = " "
    message = "Hello, world!"

    if len(sys.argv) > 2:
        if sys.argv[1].startswith("-"):
            message = " ".join(sys.argv[2:])
            option = sys.argv[1]
        else:
            message = " ".join(sys.argv[1:])
    if len(sys.argv) == 2:
        if sys.argv[1].startswith("-"):
            option = sys.argv[1]
        else:
            message = sys.argv[1]
    if len(sys.argv) == 1:
        message == "Hello, world!"
    try:
        if "ayy lmao" in message:
            l.ayylmao()
        elif option == "-n":
            l.nyan(message)
        elif option == "-m":
            l.multi(message)
        else:
            l.plain(message)
    except KeyboardInterrupt:
        exit()
