#!/usr/bin/env python3

import skilstak.colors as c
import time as t

def plain(message):
    "Normal message"
    print(c.clear + c.rc() + message + c.reset)
  
def nyan(message):
    "Nyan-esque message"
    print(c.clear)
    while True:
        print(c.rc() + message, end = "  ")

def ayylmao():
    "ayy lmao"
    print(c.clear + c.rc() + "ayy..")
    t.sleep(1)
    while True:
        print(c.rc() + "LMAO", end = "")

def multi(message):
    "Multicoloredddddd"
    while True:
        print(c.clear + c.multi(message))
    

if __name__ == "__main__":
    import sys
    option = " "
    message = "Hello, world!"


    if len(sys.argv) > 2:
        if sys.argv[1].startswith("-"):
            message = " ".join(sys.argv[2:])
            option = sys.argv[1]
        else:
            message = " ".join(sys.argv[1:])
    if len(sys.argv) == 2:
        if sys.argv[1].startswith("-"):
            option = sys.argv[1]
        else:
            message = sys.argv[1]
    if len(sys.argv) == 1:
        message == "Hello, world!"
    try:
        if "ayy lmao" in message:
            ayylmao()
        elif option == "-n":
            nyan(message)
        elif option == "-m":
            multi(message)
        else:
            plain(message)
    except KeyboardInterrupt:
        exit()
